import { describe, expect, it } from 'vitest'
import { renderScreenUi } from './screenUi'

describe('renderScreenUi', () => {
    it('renders the login screen template', () => {
        const html = renderScreenUi('login')
        expect(html).toContain('class="screen-ui"')
        expect(html).toContain('now-order')
        expect(html).toContain('邮箱')
        expect(html).toContain('密码')
        expect(html).toContain('忘记密码？')
        expect(html).toContain('微信')
        expect(html).toContain('Google')
        expect(html).toContain('注册')
        expect(html).not.toContain('创建账号')
    })

    it('renders register-password (账号密码)', () => {
        const html = renderScreenUi('register-password')
        expect(html).toContain('创建账号')
        expect(html).toContain('入口选择')
        expect(html).toContain('su-prog-step is-current')
        expect(html).toContain('下一步')
        expect(html).toContain('返回')
        expect(html).toContain('去登录')
        expect(html).not.toContain('su-prog-step is-done')
    })

    it('renders register-verify under the same create-account step', () => {
        const html = renderScreenUi('register-verify')
        expect(html).toContain('创建账号 · <em class="su-prog-sub">验证邮箱</em>')
        expect(html).toContain('you@company.com')
        expect(html).toContain('su-otp')
        expect(html).toContain('重新发送')
        expect(html).toContain('下一步')
        expect(html).toContain('su-prog-step is-current')
        expect(html).not.toContain('su-step')
        expect(html).not.toContain('su-prog-step is-done')
    })

    it('renders register-entry (入口选择)', () => {
        const html = renderScreenUi('register-entry')
        expect(html).toContain('创建账号')
        expect(html).toContain('入口选择')
        expect(html).toContain('su-prog-step is-done')
        expect(html).toContain('已具备个人消费身份')
        expect(html).toContain('进入工作区')
        expect(html).toContain('创建组织')
        expect(html).toContain('加入组织')
        expect(html).not.toContain('完成注册')
        expect(html).not.toContain('su-entry is-on')
    })

    it('renders register-create-org form within entry step', () => {
        const html = renderScreenUi('register-create-org')
        expect(html).toContain('su-prog-step is-done')
        expect(html).toContain('入口选择 · <em class="su-prog-sub">创建组织</em>')
        expect(html).toContain('公司或团队名称')
        expect(html).toContain('创建并进入')
        expect(html).toContain('返回')
        expect(html).not.toContain('su-back')
        expect(html).not.toContain('su-lead')
        expect(html).not.toContain('组织名称')
    })

    it('renders register-join-org form within entry step', () => {
        const html = renderScreenUi('register-join-org')
        expect(html).toContain('su-prog-step is-done')
        expect(html).toContain('入口选择 · <em class="su-prog-sub">加入组织</em>')
        expect(html).toContain('su-otp')
        expect(html).toContain('su-otp-compact')
        expect(html).toContain('提交申请')
        expect(html).toContain('返回')
        expect(html).not.toContain('8 位组织码')
        expect(html).not.toContain('su-back')
        expect(html).not.toContain('su-lead')
    })

    it('renders register-social (社交注册)', () => {
        const html = renderScreenUi('register-social')
        expect(html).toContain('创建账号 · <em class="su-prog-sub">基本信息</em>')
        expect(html).toContain('入口选择')
        expect(html).toContain('已通过微信授权')
        expect(html).toContain('you@company.com')
        expect(html).toContain('下一步')
        expect(html).toContain('返回')
        expect(html).not.toContain('完善资料')
        expect(html).not.toContain('可选，便于找回与通知')
    })

    it('renders forgot-verify (身份验证 · 邮箱)', () => {
        const html = renderScreenUi('forgot-verify')
        expect(html).toContain('身份验证')
        expect(html).toContain('更新密码')
        expect(html).toContain('you@company.com')
        expect(html).toContain('下一步')
        expect(html).toContain('返回登录')
        expect(html).toContain('su-prog-step is-current')
        expect(html).not.toContain('su-prog-step is-done')
    })

    it('renders forgot-code under identity step', () => {
        const html = renderScreenUi('forgot-code')
        expect(html).toContain('身份验证 · <em class="su-prog-sub">验证邮箱</em>')
        expect(html).toContain('su-otp')
        expect(html).toContain('重新发送')
        expect(html).toContain('下一步')
    })

    it('renders forgot-reset (更新密码)', () => {
        const html = renderScreenUi('forgot-reset')
        expect(html).toContain('身份验证')
        expect(html).toContain('更新密码')
        expect(html).toContain('su-prog-step is-done')
        expect(html).toContain('新密码')
        expect(html).toContain('确认密码')
        expect(html).toContain('完成')
    })

    it('renders profile (个人信息 · 移动)', () => {
        const html = renderScreenUi('profile')
        expect(html).not.toContain('个人设置')
        expect(html).not.toContain('个人信息')
        expect(html).toContain('组织信息')
        expect(html).toContain('su-layout-label')
        expect(html).toContain('su-icon-edit')
        expect(html).toContain('su-panel-identity')
        expect(html).toContain('su-hero-name')
        expect(html).toContain('张伟')
        expect(html).toContain('you@company.com')
        expect(html).toContain('su-panel-org')
        expect(html).toContain('su-panel-layout')
        expect(html).not.toContain('加入码')
        expect(html).not.toContain('su-more-menu')
        expect(html).toContain('组织申请')
        expect(html).toContain('加入审批')
        expect(html).toContain('成员清单')
        expect(html).toContain('退出登录')
        expect(html).not.toContain('>姓名<')
        expect(html).not.toContain('su-card-wide')
    })

    it('renders profile-pc (个人信息 · PC)', () => {
        const html = renderScreenUi('profile-pc')
        expect(html).toContain('su-card-wide')
        expect(html).toContain('su-pc-grid')
        expect(html).toContain('su-panel-identity')
        expect(html).toContain('su-panel-org')
        expect(html).toContain('su-layout-label')
        expect(html).toContain('个人信息')
        expect(html).toContain('组织信息')
        expect(html).toContain('su-menu')
        expect(html).toContain('su-menu-row-shell')
        expect(html).toContain('su-layout-label')
        expect(html).toContain('组织申请')
        expect(html).toContain('加入审批')
        expect(html).toContain('成员清单')
        expect(html).not.toContain('su-menu-trail')
        expect(html).not.toContain('待审')
        expect(html).not.toContain('su-count')
        expect(html).not.toContain('su-icon-edit')
        expect(html).not.toContain('su-more-btn')
        expect(html).not.toContain('su-more-menu')
        expect(html).not.toContain('su-hero-name')
        expect(html).not.toContain('加入码')
        expect(html).not.toContain('you@company.com')
        expect(html).not.toContain('个人设置')
        expect(html).not.toContain('编辑资料')
    })

    it('renders profile-edit', () => {
        const html = renderScreenUi('profile-edit')
        expect(html).toContain('编辑资料')
        expect(html).toContain('su-card-modal')
        expect(html).toContain('su-viewport-modal')
        expect(html).not.toContain('su-card-app')
        expect(html).toContain('su-avatar-edit')
        expect(html).toContain('更换头像')
        expect(html).toContain('su-icon-camera')
        expect(html).toContain('保存')
        expect(html).toContain('取消')
        expect(html).toContain('不可改')
    })

    it('renders org-info', () => {
        const html = renderScreenUi('org-info')
        expect(html).toContain('组织信息')
        expect(html).toContain('华东供应链')
        expect(html).toContain('加入码')
        expect(html).toContain('角色')
        expect(html).toContain('su-more-menu')
        expect(html).toContain('编辑')
        expect(html).not.toContain('成员清单')
        expect(html).not.toContain('加入审批')
    })

    it('renders member-list as accordion by role', () => {
        const html = renderScreenUi('member-list')
        expect(html).toContain('成员清单')
        expect(html).toContain('su-accord')
        expect(html).toContain('su-accord-owner')
        expect(html).toContain('su-accord-admin')
        expect(html).toContain('su-accord-member')
        expect(html).toContain('负责人')
        expect(html).toContain('管理员')
        expect(html).toContain('张伟')
        expect(html).toContain('王芳')
        expect(html).toContain('李明')
        expect(html).toContain('su-member-role')
        expect(html).toContain('su-select')
        expect(html).toContain('移除')
        expect(html).toContain('su-btn-danger')
        expect(html).toContain('su-paging')
        const ownerBlock = html.slice(
            html.indexOf('su-accord-owner'),
            html.indexOf('su-accord-admin'),
        )
        expect(ownerBlock).not.toContain('su-paging')
    })

    it('renders member-list-pc as tab layout ghosts', () => {
        const html = renderScreenUi('member-list-pc')
        expect(html).toContain('su-card-wide')
        expect(html).toContain('成员清单')
        expect(html).toContain('su-tabs')
        expect(html).toContain('su-tab-owner')
        expect(html).toContain('su-tab-admin')
        expect(html).toContain('su-tab-member')
        expect(html).toContain('su-member-row-ghost')
        expect(html).not.toContain('su-paging-ghost')
        expect(html).not.toContain('张伟')
    })

    it('renders member-role-confirm', () => {
        const html = renderScreenUi('member-role-confirm')
        expect(html).toContain('确认变更角色')
        expect(html).toContain('王芳')
        expect(html).toContain('管理员')
        expect(html).toContain('成员')
        expect(html).toContain('确认变更')
        expect(html).toContain('取消')
        expect(html).toContain('su-card-modal')
    })

    it('renders member-role-owner-confirm', () => {
        const html = renderScreenUi('member-role-owner-confirm')
        expect(html).toContain('确认移交负责人')
        expect(html).toContain('王芳')
        expect(html).toContain('你将自动降级为管理员')
        expect(html).toContain('确认移交')
        expect(html).toContain('取消')
        expect(html).toContain('su-card-modal')
        expect(html).not.toContain('原负责人')
        expect(html).not.toContain('张伟')
    })

    it('renders member-remove-confirm', () => {
        const html = renderScreenUi('member-remove-confirm')
        expect(html).toContain('确认移除')
        expect(html).toContain('李明')
        expect(html).toContain('确认移除')
        expect(html).toContain('取消')
        expect(html).toContain('su-btn-danger')
        expect(html).toContain('su-card-modal')
    })

    it('renders member-remove-self-confirm', () => {
        const html = renderScreenUi('member-remove-self-confirm')
        expect(html).toContain('确认离开组织')
        expect(html).toContain('将自己移出本组织')
        expect(html).toContain('确认离开')
        expect(html).toContain('取消')
        expect(html).toContain('su-btn-danger')
        expect(html).toContain('su-card-modal')
    })

    it('renders member-remove-owner-block', () => {
        const html = renderScreenUi('member-remove-owner-block')
        expect(html).toContain('无法直接移除')
        expect(html).toContain('负责人移除自身前，须完成负责人移交或解散组织。')
        expect(html).toContain('移交负责人')
        expect(html).toContain('解散组织')
        expect(html).toContain('取消')
        expect(html).toContain('su-btn-danger')
        expect(html).toContain('su-card-modal')
    })

    it('renders org-edit', () => {
        const html = renderScreenUi('org-edit')
        expect(html).toContain('编辑组织')
        expect(html).toContain('su-card-modal')
        expect(html).toContain('su-avatar-edit')
        expect(html).toContain('su-avatar-org')
        expect(html).toContain('组织名称')
        expect(html).toContain('华东供应链')
        expect(html).toContain('加入码')
        expect(html).toContain('不可改')
        expect(html).toContain('保存')
        expect(html).toContain('取消')
        expect(html).not.toContain('su-card-app')
    })

    it('renders org-applications', () => {
        const html = renderScreenUi('org-applications')
        expect(html).toContain('组织申请')
        expect(html).toContain('待审核')
        expect(html).toContain('已拒绝')
        expect(html).toContain('已通过')
        expect(html).toContain('申请加入组织')
    })

    it('renders org-applications-pc (layout only)', () => {
        const html = renderScreenUi('org-applications-pc')
        expect(html).toContain('su-card-wide')
        expect(html).toContain('组织申请')
        expect(html).toContain('申请加入组织')
        expect(html).toContain('su-app-item-ghost')
        expect(html).not.toContain('su-panel-layout')
        expect(html).not.toContain('待审核')
    })

    it('renders join-approval as accordion by status', () => {
        const html = renderScreenUi('join-approval')
        expect(html).toContain('加入审批')
        expect(html).toContain('su-accord')
        expect(html).toContain('待审')
        expect(html).toContain('已通过')
        expect(html).toContain('已拒绝')
        expect(html).toContain('su-btn-danger')
        expect(html).toContain('su-accord-pending')
        expect(html).toContain('su-accord-approved')
        expect(html).toContain('su-accord-rejected')
        expect(html).toContain('陈强')
        expect(html).toContain('su-paging')
        expect(html).toContain('上一页')
        expect(html).toContain('下一页')
    })

    it('renders join-approval-pc as tab layout ghosts', () => {
        const html = renderScreenUi('join-approval-pc')
        expect(html).toContain('su-card-wide')
        expect(html).toContain('加入审批')
        expect(html).toContain('su-tabs')
        expect(html).toContain('su-tab-pending')
        expect(html).toContain('su-tab-approved')
        expect(html).toContain('su-tab-rejected')
        expect(html).toContain('su-approve-card-layout')
        expect(html).toContain('su-paging-ghost')
        expect(html).not.toContain('su-status')
        expect(html).not.toContain('李明')
        expect(html).not.toContain('通过为')
        expect(html).not.toContain('上一页')
    })

    it('rejects unknown templates with a short error', () => {
        const html = renderScreenUi('nope')
        expect(html).toContain('screen-ui-error')
        expect(html).not.toContain('now-order')
    })

    it('renders mes-stage-list', () => {
        const html = renderScreenUi('mes-stage-list')
        expect(html).toContain('工序管理')
        expect(html).toContain('OP.UV')
        expect(html).toContain('仅用户等级 ≤3 可新增、修改或删除工序')
        expect(html).toContain('新增')
        expect(html).toContain('删除')
    })

    it('renders mes-stage-form', () => {
        const html = renderScreenUi('mes-stage-form')
        expect(html).toContain('新增工序')
        expect(html).toContain('工序代码')
        expect(html).toContain('唯一标识，创建后不可改')
        expect(html).toContain('如 010、029')
    })

    it('renders mes-flow-list', () => {
        const html = renderScreenUi('mes-flow-list')
        expect(html).toContain('工艺流程')
        expect(html).toContain('基于此创建')
        expect(html).toContain('WFP.BA.VEH.KK00')
        expect(html).toContain('预览选中')
    })

    it('renders mes-flow-create', () => {
        const html = renderScreenUi('mes-flow-create')
        expect(html).toContain('新增工艺流程')
        expect(html).toContain('暂无工序，请从上方下拉选择后加入')
        expect(html).toContain('前序（多选并行与汇合，显示工序名称）')
        expect(html).toContain('工艺拓扑图')
    })

    it('renders mes-flow-editor', () => {
        const html = renderScreenUi('mes-flow-editor')
        expect(html).toContain('修改工艺流程')
        expect(html).toContain('返回列表')
        expect(html).toContain('提交')
        expect(html).toContain('工艺拓扑图（起点在上）')
        expect(html).toContain('脏污检测(AA前)')
        expect(html).toContain('允许游离 SN')
    })
})
